[package]
name = "eterm2json"
version = "0.1.0"
authors = ["Artem Golovinsky <artemgolovinsky@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
num-bigint = "0.2"
byteorder = "1.3.1"
hex = "0.3.2"
